name: flutterapp2
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  moor_flutter: ^1.4.0
  bloc: ^4.0.0
  equatable: ^1.1.1
  flutter_bloc: ^4.0.0
  rxdart: ^0.24.0



  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  shimmer: ^1.0.1
  moor_generator: ^1.4.0
  build_runner:

fonts:
  - family: Montserrat
    fonts:
      - asset: assets/Montserrat-Regular.ttf
      - asset: assets/Montserrat-Bold.ttf
        weight: 700

flutter:

  uses-material-design: true
  assets:
    - pictures/
    - background_pics/

